# Generated by Django 2.0.6 on 2018-09-05 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Brand Name')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos', verbose_name='Brand Logo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='brand', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=40, verbose_name='Company Name')),
                ('chamberOfCommerceNo', models.CharField(max_length=40, verbose_name='second Name')),
                ('firstName', models.CharField(max_length=40, verbose_name='First Name')),
                ('secondName', models.CharField(max_length=40, verbose_name='Second Name')),
                ('address', models.CharField(max_length=40, verbose_name='Address')),
                ('city', models.CharField(max_length=40, verbose_name='City')),
                ('postcode', models.CharField(max_length=40, verbose_name='Postcode')),
                ('Land', models.CharField(max_length=40, verbose_name='Land')),
                ('OrderHistory', models.CharField(max_length=40, verbose_name='OrderHistory')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professional', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
