# Generated by Django 2.0.6 on 2018-09-05 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('name', models.CharField(max_length=40)),
                ('fitting', models.CharField(blank=True, choices=[('X', 'fitting'), ('E27', 'E27'), ('E16', '16'), ('GU10', 'GU10'), ('LED built in', 'LED built in')], default='X', max_length=40, null=True)),
                ('material', models.CharField(blank=True, choices=[('X', 'choose material'), ('metal sprayed copper', 'metal sprayed copper'), ('metal sprayed silver', 'metal sprayed silver'), ('metal', 'metal'), ('aluminium', 'aluminium'), ('copper', 'copper'), ('vineer', 'vineer'), ('fibreglass', 'fibreglass')], default='X', max_length=40, null=True)),
                ('mains', models.CharField(max_length=40)),
                ('height', models.CharField(blank=True, max_length=40, null=True)),
                ('width', models.CharField(blank=True, max_length=40, null=True)),
                ('diameter', models.CharField(blank=True, max_length=40, null=True)),
                ('colour', models.CharField(blank=True, max_length=40, null=True)),
                ('art_No', models.CharField(max_length=40)),
                ('bruto_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('transformer_included', models.BooleanField(default=True)),
                ('product_type', models.CharField(choices=[('X', 'choose type'), ('suspension', 'suspension'), ('floor', 'floor'), ('table', 'table'), ('wall/ceiling', 'wall/ceiling'), ('outside', 'outside')], default='X', max_length=15)),
                ('miscellaneous', models.TextField(blank=True, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='accounts.Brand')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.Product')),
            ],
        ),
    ]
